// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vooezewyvzszwgxyapcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvb2V6ZXd5dnpzendneHlhcGN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDIwMzUsImV4cCI6MjA1ODkxODAzNX0.fpqaeiN2i2iIMCbIPUdnqvVpHl_4zPr3kTlq9Tj3aSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);