// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxxctdgbexdhkaimkzpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4eGN0ZGdiZXhkaGthaW1renB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MDkyMjAsImV4cCI6MjA1NzI4NTIyMH0.-FK5Nk4pr1BaHW43Q7sCvW5bdp1LmVYkpuN8Rx8eyqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);